FROM htakahashi77786/centos7
MAINTAINER Hirohshi Takahashi
RUN yum -y install wget
RUN mkdir /opt/app/
RUN cd /opt/app
RUN wget http://www.apache.org/dyn/closer.lua/servicemix/servicemix-7/7.0.0.M3/apache-servicemix-7.0.0.M3.zip

